export enum SEQUELIZE_ERRORS {
  VALIDATION_ERROR = 'SequelizeValidationError',
  UNIQUE_CONSTRAINT_ERROR = 'SequelizeUniqueConstraintError',
  EXCLUSION_CONSTRAINT_ERROR = 'SequelizeExclusionConstraintError',
  FOREIGN_KEY_CONSTRAINT_ERROR = 'SequelizeForeignKeyConstraintError',
  CONNECTION_ERROR = 'SequelizeConnectionError',
  TIMEOUT_ERROR = 'SequelizeTimeoutError',
  CONNECTION_REFUSED_ERROR = 'SequelizeConnectionRefusedError',
  ACCESS_DENIED_ERROR = 'SequelizeAccessDeniedError',
  HOST_NOT_FOUND_ERROR = 'SequelizeHostNotFoundError',
  HOST_NOT_REACHABLE_ERROR = 'SequelizeHostNotReachableError',
  INVALID_CONNECTION_ERROR = 'SequelizeInvalidConnectionError',
  CONNECTION_ACQUIRE_TIMEOUT_ERROR = 'SequelizeConnectionAcquireTimeoutError',
  CONNECTION_AUTHENTICATION_ERROR = 'SequelizeConnectionAuthenticationError',
  EMPTY_RESULT_ERROR = 'SequelizeEmptyResultError',
  DATA_ERROR = 'SequelizeDataError',
  DATABASE_ERROR = 'SequelizeDatabaseError',
  WORKER_ERROR = 'SequelizeWorkerError',
  EAGER_LOADING_ERROR = 'SequelizeEagerLoadingError',
  BULK_RECORD_ERROR = 'SequelizeBulkRecordError',
  UNKNOWN_CONSTRAINT_ERROR = 'SequelizeUnknownConstraintError',
}
